image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.68.1@sha256:c332174d3691ec7df8209d8970f3b1595e0a726780d1897e52bf74a1a879f32d
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false

portal:
  open:
    enabled: true
