image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:b3f26162c717f67fa8b2363d1fecffa4d4cd3bc92936d66949008a8125b9c36b
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:dbe5894f55d4ed75b3293ac3e7a2d49ecf48781e1066a0880a244d8cab620162
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:ab11e8535a584831f945da98744d4aede1784ab3a1115dc965828607cbd2feac
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:2c82e7782632a7ab7b37eaef24f16cd16e41c46a10c6e359e4c0e0b2297c6ab8
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:ecc4814d572fe9af8cc2783963c45ed24275701851b67bc8c83a5a69ad7d2769
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:281a1812e40b70c9a741dfed2b89c3013849a5bee480d5d8fb0adda8dd362491
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:905b53bfd2fb247facc40d8d6b84cbb1d01b0a838c89ece48683363ea507ae64
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:9d9690206171b5887817edb42028dbf3df8ba4e6d00a03784be5f5e40421f11b
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:367c174ee61cac54cc3bd6fbd59475250813fc504609e327cfe901c5d38886aa
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:b7b64da40d4a9694ee4d98a6fd4a5d4e8efb2ae69dcd4a47fd4be311ab71ad97
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:9478dc6f1a0d8f798c77dd30fe09b8f77acc1ba9381f60b68ad63a4e80b7dae2
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:80a8ce95920f67ea77a35ad7248bf1764bc129534689227b198a14d7756ec678
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:477887aece6ff97db30df62b88602b604ffaeb306a67983214e656a1b119dcb0
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:088b882594ab4ac0ad5c9c959704f19ed8e49c73e7327a33ad773b670022a754
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:7d45be7b331bf7bdfada66c32594f98d77cde3598f5908f579f6c35ef1bb23c1
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:2ae76639b66ff85b158014d9e08800ede76be33e639e7f7981ca174108dc8906
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:c500f8f86e5640038166df6d7f867335250c5b2a47087c0210ce5d49a5da6cca
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:ddad41491d33f6cf832a3ef96e11fd9c730f4d45510419bb50a8b87f92cfce56
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:ee91d77c4a1b08962d38589043c60a1ee6abbb117ddfcc48fc84a1a25dc1966d
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:c18bb6093f46a5d813a424a7b5eabb0282b5e2f9f8f8c857ad160fed12a32574
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:3d243acf5bff61a2a4e01ace59efce0e765fbeb766f9962b11e9fa2294884993
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:7f671feee5d04d3bc3120270c03aa0658ce87382257237fdd53eaf615290bc95
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:e77bc438aa6506d3a259de4839692ce221bd4e37a349cc0fbf24b79b7cbd9d3b
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:01400a2e70b8cdbec9510ddfe54b2ced099e2e11934b009e009ab0275ca6dc68
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
