image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:7d504b7be4a43e04cb952e2bf93d4f9fde0b05f357d003acd00a66a1edcd67ac
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
