image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/rflood
  tag: latest@sha256:f61b43a1b4f0a5af2650902987861a0b24f3751e61cb33d55e0165aed6cada6a
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_AUTH: "false"
