image:
  repository: docker.io/jorenn92/maintainerr
  pullPolicy: IfNotPresent
  tag: 2.22.1@sha256:38b51c6420cb2533df037cb2fdf1a362421771c48cfd89ce3358381d4532b319

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"

portal:
  open:
    enabled: true
