image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-11-17@sha256:ad0ac69a1dd2627c6f5a2387f2843a54f16cab4d6fe3d51d4e8f57571d1c8ee1
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge

portal:
  open:
    enabled: true
