image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:b2da07a9765e11701c538cd612853d2bbb4e10c1838f8aa8a48bbee0d3f9545c
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
