image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.8.3@sha256:7facbd65c34ddfbd69fc14dd4c2ee022b365f671feba4863dd3c7594ea5a7c45
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
