image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/blender
  tag: latest@sha256:9651cc4dd7e776f983547f1593544306b87a8c61079f2799296afab5966bf81f
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEYBOARD: ""
            SUBFOLDER: ""
