image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 3@sha256:eeb2e8ed7f4697770da1da152a9790f3af70ef82e1698d099ecc5255ad742f2c
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
