image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-08-20@sha256:3e0245979647ecea9caf6a42c8eee483d9059cbe6c87a823943b473f1b95dc8f
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge

portal:
  open:
    enabled: true
