image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: 1.4.35@sha256:15dff2bb24182a8ae48ea5b55201a3c9230e070c1590b2b272a1344ecc4d1e72
service:
  main:
    ports:
      main:
        port: 10042
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
