image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 3@sha256:1e96c37f6c9f3f6c8dc26453348105ce5c297c9e8f46e19d2993bdce3545963c
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
