image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:b24c1fb2efd116093ca59bca519f62b6ffa056483d0b1c9e437cf8ae1095aef7
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:21e7825a8a0a862517e052abb7e3e42bff6b3afe01d19d9e98f4fa1439899855
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:c8dde629953e994710d55e9c5ca7e6f8bc062faa5ecd2a3de113133acd69bbb6
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:898288d513c4423e906f39138bb00b7eba16dc1e784716b15812b98a2b359967
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:f8e1a507568e35f6842ddec8f1e0d1dc86a230190cdbc3846c9ba1e6592595ca
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:6f89407653ec7828b2d7f1c132fedc8bc49d25f3736722010a44175f9a1d381e
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:7404ad294a55d3d49159b20ba2a3b0a0eba8c1c54e2b9d8cff4f20b8827da6f7
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:67bc5439ca282f7e5e45999ac25cebcc5159fe95546e7f6a9608242977ad6d5e
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:719809abe6e2fbe1a8483017aca76db9bae8d13bee76068354b6deca691c03c6
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:24ee8eb361b115ecc71b7fb7a40f5d48cd4e35d44fafaf1fcc4d7ef531a303aa
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:99ba87d1f0c60f71aa4ab22333adb5e4727e3700e5058235ccc265008704534f
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:9358007e8f49d101412d71673cbe98c70bcac0eb46ca76d6cb16ecd839c41c37
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:abce7520cca6423654c1b1846b51e18cdebb98ab3c2efec2c345d54c0d3d09b9
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:0819883e42e40490ef09bfc348d868a044138e4a3ca894b1ba774fe19e38c3c8
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:d232bbd408a1e3c9a94111fb21fb04fb568f2d6c27301e8d54cac8300ef81e55
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:d59c66211c690a24c8ab913de4ec2507f2a4615581aa3dd624eb775e8b558000
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:26eea886febe153ad994f84d67ffb8a1298953ace24994048662440408eca51d
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:d78a392ea649fc568ed0ca957d2c7e21cde6e0830ec1d03968954dab169987e5
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:5da47e1ab339a079f42dc7ec967f13739dd096617ef31fe292dab68e48799d0b
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:fda0992e8d63dd8bc2b9c38d6f1e958bb6886591dd32d0a0bf5b668893e9b814
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:932a0b0e7a971291580b231bdc4281b1d06957d0035fa2c734f9b7da5e0052d4
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:8d87a26a17161e978a73b6909a11c87f0fb71073ff45384bdcb7267932ba5ab5
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:a8732acf5ed15a6fc4cf2dcb5fd1a11588dea7696bc5e3a83be3a6d452863c52
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:88a1a3591c0a671f5b31184f8391d8e9906c3f261dc0dd4b0df75078ab73cd91
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
