image:
  repository: ghcr.io/sysadminsmedia/homebox
  pullPolicy: IfNotPresent
  tag: 0.17.1@sha256:82bfc025caeefb7c9fa1f638fbbbdc0b01d9539a3ec846b8f37c00e4534db436
homebox:
  allow_registration: true
  auto_increment_asset_id: true
  max_upload_size: 10
  log_level: info
  log_format: text
  mailer_host: ""
  mailer_port: 587
  mailer_from: ""
  mailer_username: ""
  mailer_password: ""
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: homebox-secret
service:
  main:
    ports:
      main:
        protocol: http
        port: 10603
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
