image:
  repository: docker.io/whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.19.0@sha256:bb69fe8dada3821a7b3be3c878be4716844d11ff6b5c9f5cfdbd340d9ab6feb9
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
