image:
  repository: ghcr.io/taxel/plextraktsync
  tag: 0.32.6@sha256:031e9cc89d12107db6758512c9abd4af083a9de041406907de5414b12ea39d60
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

plextraktsync:
  cron_enabled: true
  task: ""
  schedule: "0 */6 * * *"

cronjob:
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2

workload:
  main:
    podSpec:
      containers:
        main:
          tty: true
          stdin: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  open:
    enabled: false
