image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: 1.4.35@sha256:7ce605dd70c41e170d02310e41ed7c4e6497c25432993329cca9591cc7708434
service:
  main:
    ports:
      main:
        port: 10042
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
