# Fake external service image
image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: 3.21.1@sha256:b97e2a89d0b9e4011bb88c02ddf01c544b8c781acf1f4d559e7c8f12f1047ac3

global:
  # Ignore isStopped
  ignoreIsStopped: true

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    useSlice: false
    ports:
      main:
        protocol: https
        port: 10003
        # Target port is the port of the "external service"
        # Defaults to "port" if not set
workload:
  main:
    enabled: false
    podSpec:
      containers:
        main:
          env: {}
portal:
  open:
    enabled: true

ingress:
  main:
    annotations:
      traefik.frontend.passHostHeader: "false"
