image:
  pullPolicy: IfNotPresent
  repository: docker.io/mikenye/tar1090
  tag: latest@sha256:f2c5c5d15834792ff1907ef1981e5c84091053e615c3f09e323d3e75fc558562
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
