image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:b24c1fb2efd116093ca59bca519f62b6ffa056483d0b1c9e437cf8ae1095aef7
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:0096a9abd56557ae56e61ece833dd842827f60762c8c292ea7a4789f6a423527
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:47655322e86fa1c9cf23916d0425ff7e28cdca620082adffcafbd60026141c59
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:f0d8a66b7b6bef881cd5da80da28d692b443bcd27146cfb15cfd67ee34fb1763
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:f86d962618eefa97297ef135b9072f81bbb27209fa9983b85e64bf34cf3dad62
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:a0c1f73d211dcc9c01bbc7d6fe640d551f6cbabb14c3789ad0e818d3f06f0cb6
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:030f119470aff19ac5c970c5c9ebb7a5dca0d08e92812c72b3d161101108d93a
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:1aac94497c21063c10dfb30313f469e05c0aaa16d75304a1077dfd4c2a905e65
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:f24ac31b3b8a3e78ec942ddc9d97c08f591db47c29136fb2d76a1c60e7d58194
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:49936a894376a6f2c1d2f0442ab65c1b90e2b2edfdeffd7a6b6733c4c7771e1f
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:53ca5e015139c9e7a645e715b2adcb56787d8576baca768e81b12eacbf91bf6a
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:ec05c6f5b815d386c52856b5fa14a786e9e61cd63d459099e3913eec17ca7bb3
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:415bc3888bdb61af79b2f6559608d284fa893bd95b824752424e65c02a12ec11
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:1cb2b2995cc0c37f52080f1af20320264365c910eb40714dbc747e5efaf953be
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:4c7b9ff5e86a03c8151678533e3abe3dbf04ac3fa427a693d7154d41ced61c58
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:f3f46ed33eba5ceea666a7083a71e8e1cbc4da2687c717440ed153eadefe7c98
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:f5d877ad244a02d97f7f5b007799ec1a799246401e414a34f11c903611cab9b3
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:de508c6d0a8dfacc8138d95d628d794f21ea754edb8c41a0349d10b27a8d8c63
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:29375a33133acb86530f43af8a9ca1bb73722bb17f13c1b49844f9fecb6a3e37
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:a6b6a6023a92e39c7f56741197ce325aaf7a82b143f156f8aa1e551c3a3222d0
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:6ded386bc5c3ec51d403d40062bcd6cf3c564f074de7ab23541955de65852dd6
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:21c0b32920b9c2bb2212ca3b16732c915c1b4fedc12fab8a581a8657a2e65945
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:faea507108d2d97926d5f4d3d2a042a766e026a20ddf8565017d09683514bceb
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:199b1d11955f3963578ef8eff7a54851e72dd7e5b6883cbf8b9c64a265dd6123
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
