image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2008@sha256:0dd205d2f5d065abfb5af40527e0b253419dbbde32eeb34487bdc18428b9da59
portal:
  open:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
