image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/meeb/tubesync
  tag: latest@sha256:53b97d987b320a0acff19d66a054f3333f0a6a541d3580150bdd1c072360791d
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4848
        protocol: tcp
        targetPort: 4848
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_CONNECTION: ""
            http_PASS: ""
            http_USER: ""
            TUBESYNC_DEBUG: "False"
            TUBESYNC_HOSTS: ""
            TUBESYNC_WORKERS: "2"
