image:
  pullPolicy: IfNotPresent
  repository: docker.io/grafana/grafana-image-renderer
  tag: latest@sha256:c110c2152faf870b9c43c0a30853598609c786b772d7d3cdbc07226c19df7f70
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
