image:
  repository: ghcr.io/beryju/gravity
  tag: v0.26.4@sha256:22540ba4dba75c69d942a50beed7a83bfbb2ce2a255a1383097ad713e8d281c2
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8008
        port: 8008
  dns:
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        targetPort: 53
        port: 53
      dns-udp:
        enabled: true
        protocol: udp
        targetPort: 53
        port: 53

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTANCE_IP: "127.0.0.1"
            ADMIN_PASSWORD: "password"
            INSTANCE_IDENTIFIER: "truecharts-dns-gravity"
            BOOTSTRAP_ROLES: "dns;api;etcd;discovery;backup;monitoring;tsdb"
            ADMIN_TOKEN:
              secretKeyRef:
                name: gravity-secret
                key: ADMIN_TOKEN
            INSTANCE_LISTEN: "0.0.0.0"

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  open:
    enabled: true
