image:
  repository: docker.io/machines/filestash
  tag: latest@sha256:3abb3365455ea4369f4b43f5abc9c608b55b8e2a299bc3036ad8f6fb9431674d
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8334
        port: 8334

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APPLICATION_URL: "http://localhost:8334"
            GDRIVE_CLIENT_ID: ""
            GDRIVE_CLIENT_SECRET: ""
            DROPBOX_CLIENT_ID: ""
            ONLYOFFICE_URL: ""

persistence:
  data:
    enabled: true
    mountPath: /app/data/state

portal:
  open:
    enabled: true
