image:
  pullPolicy: IfNotPresent
  repository: adminer
  tag: latest@sha256:8f816804193e7e30f5725f4148a217dd5549579706b7d82204a26c18a32d95dc
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ADMINER_DESIGN: ""
            ADMINER_PLUGINS: ""
service:
  main:
    ports:
      main:
        port: 18080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
