image:
  pullPolicy: IfNotPresent
  repository: docker.io/lswl/vertex
  tag: stable@sha256:22fd2d2bfbc31bdfa083b4ea829d751d8ed9d9f60ffe3d3c34a7569b3ac1910d
persistence:
  config:
    enabled: true
    mountPath: /vertex
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "3000"
