image:
  repository: docker.io/machines/filestash
  tag: latest@sha256:4835651bb14808b6050ab196caa18f8e109c2e8a2ab36b52b2f163dd3209422e
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8334
        port: 8334

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APPLICATION_URL: "http://localhost:8334"
            GDRIVE_CLIENT_ID: ""
            GDRIVE_CLIENT_SECRET: ""
            DROPBOX_CLIENT_ID: ""
            ONLYOFFICE_URL: ""

persistence:
  data:
    enabled: true
    mountPath: /app/data/state

portal:
  open:
    enabled: true
