image:
  pullPolicy: IfNotPresent
  repository: adminer
  tag: latest@sha256:ff53e842ac98d12648c9c10e453ccacee427a58978f98e68fdbf20e43e81b48c
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ADMINER_DESIGN: ""
            ADMINER_PLUGINS: ""
service:
  main:
    ports:
      main:
        port: 18080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
