annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: productivity
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: "1.61.1-chr"
dependencies:
  - name: common
    version: 25.4.3
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Browserless is a web-service that allows for remote clients to connect, drive, and execute headless work
home: https://github.com/hey101/charts/stable/browserless-chrome
icon: https://truecharts.org/img/hotlink-ok/chart-icons/browserless-chrome.webp
keywords:
  - browserless
  - chrome
  - puppeteer
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: browserless-chrome
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/browserless-chrome
  - https://docs.browserless.io/docs/docker.html
  - https://github.com/truecharts/charts/tree/master/charts/stable/browserless-chrome
  - https://hub.docker.com/r/browserless/chrome
type: application
version: 11.4.1
