image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: latest@sha256:9c911ce9336c0de86d1aa59e737ad8df67c51152a1e049b8b71ac6d80bdb37ca
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST: ""
            YOURLS_DB_NAME: ""
            YOURLS_DB_PASS: ""
            YOURLS_HOURS_OFFSET: ""
            YOURLS_PASS: ""
            YOURLS_PRIVATE: ""
            YOURLS_SITE: ""
            YOURLS_USER: ""
