image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2321@sha256:c292a9527b2f8d0e9fbb6b7f43cf22f8429b41c7e78aed7b901b98cf4bcbd445
portal:
  open:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
