image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 3@sha256:45fbac229389d0ee0d2ba80c92df8a2bd5896f51950b6070b6f92e8009955268
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
