image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:0bbc166453fa8abba78a16b5cd7a66a0cda34be6d73963adb0882adc36a0297e
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
