image:
  repository: docker.io/jgraph/drawio
  tag: 28.1.1@sha256:6adc8703a35c1e8e3736d463c7b171e2e6bbb9ba56abafff708d28cde7994bbe
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
portal:
  open:
    enabled: true
