image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:f6d4481f8163d74657fad1a0d00aea3c3a8d005633c8935019c0f06e35b8ba39
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
