image:
  repository: docker.io/brandawg93/peanut
  tag: 5.9.2@sha256:b260204b251c7a8336d4af3f1e7417d084f81bf3ee7cb46d805fbf29eb73f71a
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NUT_HOST: "localhost"
            NUT_PORT: 3493
            USERNAME: ""
            PASSWORD: ""
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
