image:
  pullPolicy: IfNotPresent
  repository: docker.io/coderaiser/cloudcmd
  tag: latest@sha256:43be4b14d4e2bcb3fd88a1ab2adda01ed5ec916e32272b7c3f4d539aedaf0f15
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
