image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:e2f2e34a9f7c0256175f20daced27d2b8c266c6b9c4971a274e297785de129b2
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
