image:
  repository: docker.io/privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.5.7@sha256:eaca2dad585ea9ee73aa752c71e0897afd017a008e7871b68f6a07c00e064a8a

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"

portal:
  open:
    enabled: true
