image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 3.6.5@sha256:a313f996a3847038665cdcbecd4ae14254281d06385cc178949fa3fd58b55a56
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
portal:
  open:
    enabled: true
