image:
  repository: ghcr.io/elfhosted/jackett
  pullPolicy: IfNotPresent
  tag: 0.23.23@sha256:cc8cb0b731c0658210ef841a864d0acc9dc2ae803a663fc0b096be97a89cc242
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
