annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: management
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: "2.27.0"
dependencies:
  - name: common
    version: 26.4.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Container management made easy
home: https://github.com/hey101/charts/stable/portainer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/portainer.webp
keywords:
  - portainer
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: portainer
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/portainer
  - https://github.com/truecharts/charts/tree/master/charts/stable/portainer
  - https://docs.portainer.io/start/install-ce/server
  - https://docs.portainer.io/start/install/server
  - https://hub.docker.com/r/portainer/portainer-ce
  - https://hub.docker.com/r/portainer/portainer-ee
type: application
version: 10.9.13
