image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:7bbbfcf589377b2d1f71703b9c3af6e9e80ebe0b2e91d1f4c1ebc68299efbe75
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:db6435a8fa14769b5f7ff41fe1eef5eb5464a66ed584d62df287734476d3902f
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:a11f1d7e5cb8541e70fd2ca52721ef97561f449d1e5aab28ceb09c16eb772db2
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:5575b7974a7a973fb24e16723cb9301069c62fa2a33d990d97801e88990f709b
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:d51950b907cd8d0c6ce4a2277d47f76008638e981cf13e2092f2a84c55b8004c
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:6ef9bf500ec9f5c1209a217838a88c37fb76df9238d6dcb152fd499f1e0f6cff
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:d79bee610bd982303a01e91984196fbca022d0a13993bb40a6f89b11bf89b650
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:753b0796ec027d730cdf41a5d6d5d002a628bd982d50f928d4ac7ce6da721833
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:9e8c099d1aeef11b2244b0850e1c60abea58aadc17a4c3d2eb1b366112da1cfc
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:2e61e7c78895c561a2a8f9b0c49e7e353279e44688f8995b1f08015bd040a493
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:fa87dfd544a0a161de87b9a2fa3ace598f4f92a374ec4853d568ac07cfdf9ec7
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:5221f0cc55eaf2e11c4ddc359519c06d98be7c5895b6fa6ef6ec9c7c47217d1b
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:b744fbd78df8023733439449f4d719788c4c7f60c1abaf4557a86f9327d4209e
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:518e340fd6b02fce8c222b7bd64da365d26eb9ac6748736864ab3a14ebbf9b1b
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:dfefa1bfa62bb6a156b9302e6b84a543858269e6d18b3e542f0550a2bf9e02ef
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:2e777cc426e1eff55f7b4592640b5e41cb74e65d2914ba625612e04cf9a15a4b
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:3ef53ca887ae8d54eec1c012e4e0d081e5c06a036da8212078d586e46bef5188
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:a75301fe92f3a35c346e893167672180c8f0f748752d455b0bfabb86a50e8b39
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:56e583da788efbf4437938b908b2803b656fb37909080734cb20e07cdff0986f
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:f9423210b48eda24c9967ba26b9c18f604e062fdeb1c8d0f363217f0fde5d9cc
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:13009b56e54471917e6d54623b5b4542f292a964d4d403a234f1fa93190c328e
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:88971f557702f53e1d3b2801be7d5ade711ebdc8474aa7ef650c74bcfbbbf555
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:e3d7376c9f30763310b5e35c74d37aa1617fa1da85998b1b4428edd25e6e80e6
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:54d9079d38aee34063206fb5b233ea7c8801108756fb61aa0680eabdfad91dcd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
