image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: latest@sha256:64bc9985d0b50c0d35d05829e7cc4391d2148186d7276b8799eb406d0eff26d4
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST: ""
            YOURLS_DB_NAME: ""
            YOURLS_DB_PASS: ""
            YOURLS_HOURS_OFFSET: ""
            YOURLS_PASS: ""
            YOURLS_PRIVATE: ""
            YOURLS_SITE: ""
            YOURLS_USER: ""
