image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:1e96c37f6c9f3f6c8dc26453348105ce5c297c9e8f46e19d2993bdce3545963c
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
