image:
  pullPolicy: IfNotPresent
  repository: docker.io/coderaiser/cloudcmd
  tag: latest@sha256:ee0c297307fe1de97fe6b7cc4924c0aaa6ee8b0adbe32dff50e5ca4aca24bd35
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
