image:
  pullPolicy: IfNotPresent
  repository: docker.io/grafana/grafana-image-renderer
  tag: latest@sha256:37d03fc58922f0a933a7a02e070e76ad8dc28bfb7a55c05ca898e01875fc8939
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
