image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:45fbac229389d0ee0d2ba80c92df8a2bd5896f51950b6070b6f92e8009955268
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
