image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/blender
  tag: latest@sha256:439e3b574836f31da5bafc1f5764dda093c18bb2fa4c903420506b73d1bdc8bb
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEYBOARD: ""
            SUBFOLDER: ""
