image:
  repository: docker.io/difegue/lanraragi
  tag: v.0.9.50@sha256:ed97c2e973f0034a898472177736382a28b09c57c1cbeabbef32692d243325da
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10177
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/database"
  content:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/content"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LRR_UID: "{{ .Values.securityContext.container.PUID }}"
            LRR_GID: "{{ .Values.securityContext.pod.fsGroup }}"
