image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: latest@sha256:6724214362b977adb513d6310df6e688d005ead846e7d3cb72292fac5239c27e
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST: ""
            YOURLS_DB_NAME: ""
            YOURLS_DB_PASS: ""
            YOURLS_HOURS_OFFSET: ""
            YOURLS_PASS: ""
            YOURLS_PRIVATE: ""
            YOURLS_SITE: ""
            YOURLS_USER: ""
