image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/pyload-ng
  tag: latest@sha256:5e4fd6857a782ebc69ac7b93b55c42b460ca4afd94d8b7760c0af911002a059c
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: tcp
        targetPort: 9666
workload:
  main:
    podSpec:
      containers:
        main:
          env:
