image:
  pullPolicy: IfNotPresent
  repository: docker.io/mikenye/tar1090
  tag: latest@sha256:409c65eeaa1b93e31ee7996b1f0f413d941419347a240547bddc272224590e20
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
