image:
  pullPolicy: IfNotPresent
  repository: docker.io/hauxir/imgpush
  tag: latest@sha256:7a7b134999dcf8017a3b4fecad183caf840074da06269d45f4c0d92c7712026f
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
