image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:4f4e40fdf0e855d127591f1e9900ff2d0ceecc52925e9d8b6af100491356bbc2
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
