image:
  pullPolicy: IfNotPresent
  repository: docker.io/grafana/grafana-image-renderer
  tag: latest@sha256:31a9e2185668d865ac92a2dde51a17069eb2ca9325272a211ea8239d61572b65
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
