image:
  pullPolicy: IfNotPresent
  repository: docker.io/mikenye/tar1090
  tag: latest@sha256:3d18d9c787c77ba9d9da8482b9d72bf3e6de2509b422bd59fcee58c48b87be71
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
