image:
  repository: docker.io/revenz/fileflows
  tag: 25.05@sha256:4ae44a7c4dfd0e46bef095ec096726dc53f7ca20325204fd835d6a60f3e8914b
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
    privileged: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10242
        targetPort: 5000
persistence:
  data:
    enabled: true
    mountPath: /app/Data
  logs:
    enabled: true
    mountPath: /app/Logs
  temp:
    enabled: true
    mountPath: /temp
  media:
    enabled: true
    mountPath: /media
portal:
  open:
    enabled: true
