image:
  repository: docker.io/jgraph/drawio
  tag: 28.1.1@sha256:4acb424ddcf38d2d3319dda09fdc9c58f9e623c855df68c1046756eb6cf27579
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
portal:
  open:
    enabled: true
