image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/rflood
  tag: latest@sha256:75d8d580248049ca676d500a48528ca09b6db171b643050f38149ded2c613293
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_AUTH: "false"
