image:
  pullPolicy: IfNotPresent
  repository: docker.io/hexxa/quickshare
  tag: latest@sha256:0b2fe173eabb1b242c0d8c0773b88764c529639d5d4a443e2ab898c7dc4c82c2
persistence:
  storagedata:
    enabled: true
    mountPath: /quickshare/root
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8686
        protocol: tcp
        targetPort: 8686
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DEFAULTADMIN: admin
            DEFAULTADMINPWD: "1234"
