image:
  repository: ghcr.io/elfhosted/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2162@sha256:222feb87a36d7eb98437538dda59bffc372a926c147c2977c91228d90de6620a
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
