annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: "2.45.2"
dependencies:
  - name: common
    version: 26.2.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Wallos - Self Hosted Subscription tracker
home: https://github.com/hey101/charts/stable/wallos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wallos.webp
keywords:
  - dashboard
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: wallos
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/wallos
  - https://github.com/truecharts/charts/tree/master/charts/stable/wallos
  - https://ghcr.io/ellite/wallos
  - https://github.com/ellite/Wallos
type: application
version: 6.7.13
