image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: latest@sha256:301d689fd5de7bf996523904eab538b32a1d75fad297ba377e0b3826de9265c1
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST: ""
            YOURLS_DB_NAME: ""
            YOURLS_DB_PASS: ""
            YOURLS_HOURS_OFFSET: ""
            YOURLS_PASS: ""
            YOURLS_PRIVATE: ""
            YOURLS_SITE: ""
            YOURLS_USER: ""
