image:
  pullPolicy: IfNotPresent
  repository: docker.io/yacy/yacy_search_server
  tag: latest@sha256:14f22a5b51bca7a924f80d25c1551005700f9984cd8934e9ade5b78febc6c521
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
