image:
  pullPolicy: IfNotPresent
  repository: docker.io/songkong/songkong
  tag: latest@sha256:be5be2141cf4484692adb4beee7dfceff26123fbe01ea534f5b39719a725383b
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
