image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:41b89b4f64c18c441b4a8dfd9e729203c797d1d9e662541272fcb4f75570aa63
persistence:
  download:
    enabled: true
    mountPath: /download
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
