image:
  pullPolicy: IfNotPresent
  repository: docker.io/phpmyadmin/phpmyadmin
  tag: 5.2.3@sha256:cb698865b646fd5968b17ce32aef6a7060317d1115ea975690a1b1c6b383e4c3
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            PMA_HOST: 192.168.70.99
            PMA_PORT: "3306"
