image:
  repository: ghcr.io/elfhosted/emby
  pullPolicy: IfNotPresent
  tag: 4.9.0.56@sha256:ff985b0608d52ad00a03f88361b1f7b8619d91b7096aec33edec20173023cc8f
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
