image:
  repository: docker.io/revenz/fileflows
  tag: 25.02@sha256:2379e777eabc6a002d6f9107938d43e59ffc7c5311fc031e39340205a6802427
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
    privileged: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10242
        targetPort: 5000
persistence:
  data:
    enabled: true
    mountPath: /app/Data
  logs:
    enabled: true
    mountPath: /app/Logs
  temp:
    enabled: true
    mountPath: /temp
  media:
    enabled: true
    mountPath: /media
portal:
  open:
    enabled: true
