image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.8.3@sha256:607f1ddfa756fbf7f7802e65fbf1519b9b847118adc9491f27fb0a6819a368a2
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
