image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: latest@sha256:ee3b521424f480d9e829e48eb8f7df3b9348cd4f550b961f83cd4fb5667c625f
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:e4956b4f2c1918bab989b9e85b5637a97d29b283812c2657b230e5a6a9194c13
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:f114597249cffb5013914a3b418df01db2528cf2b02497e491c627c812f69ae8
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:1976c3bd57d9f24dd618471e3f3070d0fb02d4e6a0017247e516bb0d8d35a572
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:c121f24b5ae762d590f81e66aaad3aa5edddcc66d9e59530f6210cc6b8202253
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:efc27bb1b0a536bc678c7033c629b0aa52a9df9e392be4c77dcc231cb0766a8f
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:c56ab5173933b86a8b0e23cbace17bde0c6686e2a4eec9f603d3ef61ee7ceadf
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:4ad2b3a305aa967240998fda66a6f94a6a23313d33f4f56fc8da39045ba5dc78
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:9e8befa2c822c00a7d0ad6f1f295523d79671ad0c907939bbdf885af65480331
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:5c7c4dc0c0038c715f034908afa9982a7d5bed6f6872a8fd961c361a1d9e5117
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:1789c15fc993b54e53d93b9e87ac63d3acd780590b7b4fd235c05b4856b9efd2
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:430ad59cbe20cc0ca5cc73b30313fc7eebb4f0262d212f9e1f8234e4d83d3072
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:0e5e86985d7d488f5539b11d957c3dd2fcc9f9d38c0750c3e69f7f12dfeccfaa
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:fcdbf4b9b797aace2090f8a48507ff79e69b6581e69a23c3d9b9f14b594ac542
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:81b55aedcf62c2d6085c455cbf5eb8dace869796ea2dfa086291aee7d8749588
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:af7055b42fe66c8c0afc677b2ea4e4ee0c5f87bf0c03f8b8e4adac1515aa0d37
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:af1ed1a641340e4e4d5f7a12308eb758ba5ef076ee8ffa2c25342ae7800e3837
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:a61d9766f8885eaecd08932c46ea9b3331a89238e955c35b7577485f3817363e
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:b068a1502323f1d3e0eee8d1e697fcd81733a996363db70fd687f285881214ec
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:8988ae055e7b37781b21c46f7445d13c4f853345eb84d19854b29fec6565fd8e
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:7eafe3a42b0c95572620784281674ce7ef501ff3afad7f509feceb7de11d47a0
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:262b12d662238777e1daaab79cb95702c0d8eaf958ffb40790566f117524ae9e
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:8132fceef5193f0b386616cba61c62511a9382ffae1c2030d7cc65479d78af07
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:5bb820db6e3d851c74c6205bf6ee80d8d0d236b71bd37bf67909ce27d1ed051e
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
