image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:b25393956a2e693711e9de978f5a884c88f51064d64bb48e7f699fbe75d430b6

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: true

cloudnative-pg:
  monitoring:
    # -- Specifies whether the monitoring should be enabled. Requires Prometheus Operator CRDs.
    podMonitorEnabled: true
    grafanaDashboard:
      create: true
      # -- Allows overriding the namespace where the ConfigMap will be created, defaulting to the same one as the Release.
      namespace: ""
      # -- The name of the ConfigMap containing the dashboard.
      configMapName: "cnpg-grafana-dashboard"
      # -- Label that ConfigMaps should have to be loaded as dashboards.
      sidecarLabel: "grafana_dashboard"
      # -- Label value that ConfigMaps should have to be loaded as dashboards.
      sidecarLabelValue: "1"
