image:
  repository: docker.io/brandawg93/peanut
  tag: 5.9.0@sha256:c3de1f218ae99ae77e1501bdb3981f9269fc43835bd5c34a070cda1983982822
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NUT_HOST: "localhost"
            NUT_PORT: 3493
            USERNAME: ""
            PASSWORD: ""
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
