image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/autoscan
  tag: latest@sha256:722a5037a10ac954198b0262dced16a1c6f83a05ce2f59974f63f7266d3a7053
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3030
        protocol: http
        targetPort: 3030
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PLEX_LOGIN: ""
            PLEX_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
