image:
  repository: lscr.io/linuxserver/calibre-web
  pullPolicy: IfNotPresent
  tag: version-0.6.25@sha256:af0f715c498db314137a278d6184df95a074a66a26a87365b8e02786fc5ed815
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8083
        protocol: http
        targetPort: 8083
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
