image:
  repository: docker.io/bitnami/memcached
  pullPolicy: IfNotPresent
  tag: 1.6.38@sha256:17f1d4c8733c1ee203114b2c1295f91f8c949d4fc0f78d1c18f1cd8d681e53e1

includeCommon: true
service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
portal:
  open:
    enabled: false

configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
