image:
  repository: docker.io/edgd1er/webnut
  pullPolicy: IfNotPresent
  tag: latest@sha256:8f81c665472bb59ea1586853b15aafc6a2811cc1285d6ce1d2e88a4230e937f3
service:
  main:
    ports:
      main:
        port: 10585
        protocol: http
        targetPort: 6543
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            UPS_HOST: "127.0.0.1"
            UPS_PORT: 3493
            UPS_USER: monuser
            UPS_PASSWORD: secret
persistence:
  config:
    enabled: true
    mountPath: "/config"
