# Fake external service image
image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: 3.23.2@sha256:c93cec902b6a0c6ef3b5ab7c65ea36beada05ec1205664a4131d9e8ea13e405d

global:
  # Ignore isStopped
  ignoreIsStopped: true

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    useSlice: false
    ports:
      main:
        protocol: https
        port: 10003
        # Target port is the port of the "external service"
        # Defaults to "port" if not set
workload:
  main:
    enabled: false
    podSpec:
      containers:
        main:
          env: {}
portal:
  open:
    enabled: true

ingress:
  main:
    annotations:
      traefik.frontend.passHostHeader: "false"
