image:
  pullPolicy: IfNotPresent
  repository: docker.io/wabayang/jelu
  tag: latest@sha256:20388c3edc90017dbfe36e7ec707ff5b5e9171e8c787bd036693254696bbec33
persistence:
  config:
    enabled: true
    mountPath: /config
  databasepath:
    enabled: true
    mountPath: /database
  imagespath:
    enabled: true
    mountPath: /files/images
  importspath:
    enabled: true
    mountPath: /files/imports
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 11111
        protocol: tcp
        targetPort: 11111
