image:
  pullPolicy: IfNotPresent
  repository: docker.io/searxng/searxng
  tag: latest@sha256:ccd0d954936363db5cd017011dd541e63c9086c089e244f8f37aa18ee6857252
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BIND_ADDRESS: '{{ printf "0.0.0.0:%v" .Values.service.main.ports.main.port }}'
            INSTANCE_NAME: SearXng
            BASE_URL: ""
          probes:
            liveness:
              path: /healthz
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              path: /healthz
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    capabilities:
      disableS6Caps: true
      add:
        - SETUID
        - SETGID
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /etc/searxng
portal:
  open:
    enabled: true
