image:
  repository: ghcr.io/linuxserver/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.35@sha256:47a3ae9c17e095f3970fdd70314cdf87852fb1a8e4f04714f9a4a71d4b15393e
service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088
persistence:
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            AUTH_LIST: ""
