image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  pullPolicy: IfNotPresent
  tag: 0.51.2@sha256:cef817fd174d533b8032b3e6ded4bed72755929b81c33fb4e95b3945d7103752

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5000
        port: 5000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_URL: ""
            USE_X_SETTINGS: true
            HIDE_REFERER: true
            FETCH_WORKERS: 10

persistence:
  datastore:
    enabled: true
    mountPath: "/datastore"

portal:
  open:
    enabled: true
