image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:b6cd517b7eaf6cf51b9d3110f21b1eca88bb49d75ff442815969e924f7d7c118
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:149f7943b15fd9a2fde93289cbd10528218e4a00ec57ce616ecd386d8cbbde6b
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:a6806c064c8d32fc4d99f2e6721f0d0197230b516d0d252930d9e48103247a0e
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:f13dea1882a973e982766872d30881a588bf9ae63072cc003a8e04936082b9b4
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:d51950b907cd8d0c6ce4a2277d47f76008638e981cf13e2092f2a84c55b8004c
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:de14e2ffc0f36584d07def29da8a0d4ed5428e551332f9a1f948c97c12205580
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:5458882c267349e29c1ebb758db2a27144ba1784fafc56c1b70e803eb6d9b695
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:c94849e4bb72a5b539f0b8336c115de75ecf55640bed141d7bcd096ee998b0d9
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:4ce02bdb89318a136d37d5a21207f0f599aae0de07637b321c87d32ce443b4fa
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:fd817b72ac30ef403307f54703220be2bedf6360819e5ab70a119a1945e3a48c
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:a8e7f72de739ba78a4626b97835eb53c64879cfed02e0b74da116d4c1cb4b748
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:d469da7eeac50cdf227ade94b2c878a02022e89d72024c0555f55b1637277174
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:b744fbd78df8023733439449f4d719788c4c7f60c1abaf4557a86f9327d4209e
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:757ce8dbfa58465555940ca843e2bfbd8e1454b4b2614cae31d3f8e08ac94255
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:0a48242b1a9f498c0d71a63cbbb15dac315f044c865f8ebfab353bc6fb672fdd
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:4ee45ba2c04989afcc8ba943f0bd1effd094a8c39ad301f56de3aaa8100f716c
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:3ef53ca887ae8d54eec1c012e4e0d081e5c06a036da8212078d586e46bef5188
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:a75301fe92f3a35c346e893167672180c8f0f748752d455b0bfabb86a50e8b39
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:56e583da788efbf4437938b908b2803b656fb37909080734cb20e07cdff0986f
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:4bd8ca2ed93456957bcdb6f92aba10f4fc111f73b17c261b46511ca5d4f05742
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:13009b56e54471917e6d54623b5b4542f292a964d4d403a234f1fa93190c328e
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:88971f557702f53e1d3b2801be7d5ade711ebdc8474aa7ef650c74bcfbbbf555
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:e3d7376c9f30763310b5e35c74d37aa1617fa1da85998b1b4428edd25e6e80e6
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:a7a2a142b770560b23db4d06a66653445181296a839441a2bdbb4f6a770c7125
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
