image:
  repository: docker.io/machines/filestash
  tag: latest@sha256:c9d2f5782ce00004a4ffe73f6e7c67605c37ad72aa7d0026e42fceff74802e0b
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8334
        port: 8334

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APPLICATION_URL: "http://localhost:8334"
            GDRIVE_CLIENT_ID: ""
            GDRIVE_CLIENT_SECRET: ""
            DROPBOX_CLIENT_ID: ""
            ONLYOFFICE_URL: ""

persistence:
  data:
    enabled: true
    mountPath: /app/data/state

portal:
  open:
    enabled: true
