image:
  repository: lscr.io/linuxserver/calibre-web
  pullPolicy: IfNotPresent
  tag: version-0.6.25@sha256:d3ed33150a025511e97d109e5b755cc69ddfac8cf887941249fc435efc60db62
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8083
        protocol: http
        targetPort: 8083
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
