image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.26.3@sha256:956682095c65d891ef4d85736ce6dbaf562710fa1210aeb7c2415898022b4cae
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
