image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:609ced5ee6227dc40c1b368eaed687d531e407149c603d0531263ac71e13a428
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
