image:
  pullPolicy: IfNotPresent
  repository: docker.io/grafana/grafana-image-renderer
  tag: latest@sha256:e38292167e8427674651b672c46a5394509db35926889db7df9e6e3cbc3b6138
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
