image:
  repository: ghcr.io/hotio/cloudflareddns
  pullPolicy: IfNotPresent
  tag: latest@sha256:125d9a09788c5a7ef507a93fd182b918e14162e6704c3105627761142a0d0c0f
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
cloudflareddns:
  user: your.cf.email@example.com
  api_token: ""
  api_key: ""
  api_token_zone: ""
  interval: 300
  detect_mode: dig-whoami.cloudflare
  detect_override: ""
  log_level: 3
  host_zone_record: []
  # - domain: example.com
#   zone: A1jajaja
#   record: A
# - domain: foobar.com
#   zone: B1aksksa
#   record: A
# - domain: foobar.com
#   zone: Cs11kdkkasks
#   record: AAAA

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secret"
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
