image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:b25393956a2e693711e9de978f5a884c88f51064d64bb48e7f699fbe75d430b6

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: true

manifestManager:
  enabled: false
