image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 1.7.50@sha256:feeeea2b2b4a43b795dce3db0fe57871d05a522905edaad782373fa6047bab68
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
