image:
  repository: itzg/mc-router
  pullPolicy: IfNotPresent
  tag: 1.32.1@sha256:a8ecab0da82c2410cc3f5321092ce8f8b2e617a3059d1a505247ef4fc39b36a4
service:
  main:
    ports:
      main:
        port: 25564
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25565
mcrouter:
  host_minecraft: []
  #  - "minecraft.local=minecraft-java.ix-minecraft-java.svc.cluster.local:25565"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secrets"
          env:
            API_BINDING: ":{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.minecraft.ports.minecraft.port }}"
portal:
  open:
    enabled: false
