image:
  repository: ghcr.io/ich777/megasync
  tag: latest@sha256:a2fa5709c8266a3918b51a37a9ec70436120bd368b70b7530f651a115ef3b063
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATA_DIR: "{{ .Values.persistence.data.mountPath }}"
            CUSTOM_RES_H: "600"
            CUSTOM_RES_W: "800"

persistence:
  data:
    enabled: true
    mountPath: /data
  hostpath:
    enabled: true
    mountPath: /mnt/host
    readOnly: true

portal:
  open:
    enabled: true
