image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/autoscan
  tag: latest@sha256:4172424f7bb1f6b6cfa148341b8fbec3f399c76ab05c031c7f2af56675594dd4
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3030
        protocol: http
        targetPort: 3030
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PLEX_LOGIN: ""
            PLEX_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
