image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:eeb2e8ed7f4697770da1da152a9790f3af70ef82e1698d099ecc5255ad742f2c
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
