image:
  pullPolicy: IfNotPresent
  repository: searxng/searxng
  tag: latest@sha256:00fde56920c0ce415fe545e1e8e9d349f04c583418703c0576f395e1b28544c4
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BIND_ADDRESS: '{{ printf "0.0.0.0:%v" .Values.service.main.ports.main.port }}'
            INSTANCE_NAME: SearXng
            BASE_URL: ""
          probes:
            liveness:
              path: /healthz
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              path: /healthz
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    capabilities:
      disableS6Caps: true
      add:
        - SETUID
        - SETGID
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /etc/searxng
portal:
  open:
    enabled: true
