image:
  pullPolicy: IfNotPresent
  repository: docker.io/bsyed/troddit
  tag: latest@sha256:fe8a5355c642b139df3302b0d8994e2b3a671985ef4c9124ef04dff51fc5c92b
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLIENT_ID: ""
            CLIENT_SECRET: ""
            NEXTAUTH_SECRET: ""
            NEXTAUTH_URL: ""
            REDDIT_REDIRECT: ""
