image:
  repository: docker.io/haveagitgat/tdarr_node
  pullPolicy: IfNotPresent
  tag: 2.35.01@sha256:6a4c8e3bfb6ca72c3c1ffa833afe1e48b513bc6fba4099b858733f4181586cda
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            # User Defined
            nodeID: "myFirstTdarrNode"
            serverIP: "0.0.0.0"
            serverPort: 8266
