image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:ce138f320a4fd83a553ad766476910f4bf23704e0e86796dadbf8dc8a6834710
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
