image:
  repository: docker.io/fallenbagel/jellyseerr
  tag: 2.4.0@sha256:ae1703c66b0fc12bfcc8cba339a77044246a93f86cc8ea53665e88b3218f111f
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
