image:
  pullPolicy: IfNotPresent
  repository: docker.io/hauxir/imgpush
  tag: latest@sha256:1ed32e8b0a8ad9d1674a33d6a6c8f951bfd301c808da21bc03e42f2273b2e58c
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
