image:
  repository: ghcr.io/elfhosted/nzbget
  pullPolicy: IfNotPresent
  tag: 25.4@sha256:179503ae58c3020744e35badbe25c071832609b09d31409c9ed109987a5f8a97
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
