image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:84af7bc8a2265fa109f149bcf0543c6c47d201f86f56ce9b37ed470c807d3db8
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
