image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:a783efb9872018cf6e4086f16e90dbcc20c53f4f6ace1c2b6b2c0c75901d464b
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:fdc43c9fdee5dfc7ba6835a5178816b5b7c4e5df84498b5d460af806056dd484
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:9d0248117e3358f8bd2895684744d56f231fd0f5ac21103addc59dee973d9b42
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:822df48435c05ffbb5c829a7691b6a05566cdd62f4634b548c38a9f633e6be3b
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:72176246a250a103eb1d26256815021fd23f7194874756a373129cf3d9da6a00
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:34dca2e09bef51ca2b54aa4b140af277483ec6de8dade9729c8097e3969c78c8
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:9433f5b308600e1eb5af64ba6fff8d2abcf5f04045caffd1c32640d9609aeb0c
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:932d35959c9b55fd6ab469dab071b055c65c27732a517b03d1ad3ae9ab497fae
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:e3f2e95e6eb78a059baac2aa1de8185f071bbeb0374df2394a3e1a3d3ff96ba9
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:5c469760f7ab629d1925062f2f711ff463c825c3a9115461011bc944561eae53
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:86c3fa671e8786f6a093aabf025ccd45868fc41d40399a4a6598234b7ac4452f
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:98049519826337e81dbb5081d70815c9c499cb6a609f880fbe38778f17b07457
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:313a61a0c84722f72c991923a4736f70de625e098942d39635ef7e808c3db002
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:00cfb12eb60eda2f431b05c67f03e7fa3ff53c0b391b12879be86c63dc0278ca
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:cfa9d8228e8e2326b08d4809fd17317c1658536a9c7e3bdb27424ef13543512b
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:38c842ef5c27d469cf4f6abbff936475a1237082b66dcbb55e3f04db2866c106
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:2d8196dac31f095eeb93410016ad5af717c268e3e0c6bce94e7ac44ea121f7cc
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:cb4733e58b80828e8b98090e32ced6f88337dcfcf419d9cae79672dc2983d5f4
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:08c7648a1ee7e1d0f028ca852bf71f7d7af940b1d52cf8b820d2164bc60ef33c
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:32f2745a26673016125d674e9c5737c136ced18989691d37ff2060a6729069c9
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:b9d56976479f0b62d729877f1fa037ba938adf1f962cb15ef7aebd5fdf9436bb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:23cec97b237b306cce9eed30bf9e6a8a29c9d4ef7f4f4af13239473b7f53f177
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:8b83868d35fd09a8ee8c76fe37cbed3e56a2eae5505ba9a9f55bacad9ee9d0d6
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:7385b135f5400ca6706600d01af7fd624e3150dd29d28de84869d22ba1a4ee38
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
