image:
  repository: docker.io/privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.5.6@sha256:c005899dce088f1e584202ff89f550e7473c75831b5e1bd8891facb1ae3c3af3

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"

portal:
  open:
    enabled: true
