image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/rflood
  tag: latest@sha256:cd02db909266aaff7053d730970e119e8944faeb16d7389d469c12821f5c4d3d
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_AUTH: "false"
