image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/rflood
  tag: latest@sha256:5a483e2d941efe2635b4ddd19a267b6b72a1ed3321996d98d8a6ecdee1c81dcf
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_AUTH: "false"
