annotations:
  max_scale_version: 24.04.2.5
  min_scale_version: 24.04.0
  truecharts.org/category: minecraft
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
  truecharts.org/SCALE-support: "true"
apiVersion: v2
appVersion: "1.26.0"
dependencies:
  - name: common
    version: 27.1.3
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Lightweight multiplexer/proxy for Minecraft-Java servers.
home: https://github.com/hey101/charts/stable/mc-router
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mc-router.webp
keywords:
  - mc-router
  - minecraft
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mc-router
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/mc-router
  - https://github.com/truecharts/charts/tree/master/charts/stable/mc-router
  - https://github.com/itzg/mc-router
  - https://hub.docker.com/r/itzg/mc-router
type: application
version: 6.3.27
