image:
  repository: ghcr.io/linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:55e552d8e91bd83f51af3fbbf93b512b38309f3cca90ca995bab9a292c5fb56b
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
