image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-12-12@sha256:9ee07d2f4b5e074efd73732f899f6e0568c54cadd49784f8b865eb9d0643e3ed
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge

portal:
  open:
    enabled: true
