image:
  repository: docker.io/fancybits/channels-dvr
  pullPolicy: Always
  tag: latest@sha256:6a441a02a2acdaea38ffc0412033c416774504e1183a231134fa3eb87aa44b9d
tveImage:
  repository: docker.io/fancybits/channels-dvr
  pullPolicy: Always
  tag: tve@sha256:3eb3d95a62b1f41dac3a8f3d61758755d1b9e3751a5e7cfe8f331b1f4bfa607a
service:
  main:
    ports:
      main:
        port: 8089
        protocol: http
        targetPort: 8089
persistence:
  config:
    enabled: true
    mountPath: /channels-dvr
  recordings:
    enabled: true
    mountPath: /shares/DVR
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              port: 8089
              type: http
            readiness:
              port: 8089
              type: http
            startup:
              port: 8089
              type: http
updated: true
