image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:05515b7c4485fc4816679a60a97c794e27c0c4ceab788c58ae003461be7a158a
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
