image:
  repository: ghcr.io/linuxserver/mysql-workbench
  pullPolicy: IfNotPresent
  tag: 8.0.42@sha256:7d37a46f068a649303e27dda071ea1dc0aae5228d00b03486a9cc46a0a61a318
service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: http
        port: 10134
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      add:
        - IPC_LOCK
    runAsUser: 0
    runAsGroup: 0
