image:
  repository: lmscommunity/lyrionmusicserver
  pullPolicy: IfNotPresent
  tag: 9.1.0@sha256:fed4baa9a465656b9b56993ecb479e9c68b878bb752afa18166b0556aedfd6ab
service:
  main:
    ports:
      main:
        port: 9000
  cli:
    enabled: true
    ports:
      cli:
        enabled: true
        port: 9090
        targetPort: 9090
  playertcp:
    enabled: true
    ports:
      slimprototcp:
        enabled: true
        port: 3483
        targetPort: 3483
  playerudp:
    enabled: true
    ports:
      slimprotoudp:
        enabled: true
        port: 3483
        protocol: udp
        targetPort: 3483
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"
