image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:a783efb9872018cf6e4086f16e90dbcc20c53f4f6ace1c2b6b2c0c75901d464b
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:fdc43c9fdee5dfc7ba6835a5178816b5b7c4e5df84498b5d460af806056dd484
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:d67149e803be08b6c7ba384350913a1daf4d8da065a0150b7c9c4e1478ea424d
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:822df48435c05ffbb5c829a7691b6a05566cdd62f4634b548c38a9f633e6be3b
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:72176246a250a103eb1d26256815021fd23f7194874756a373129cf3d9da6a00
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:d82ddaecc8f3dcba50f80782a2180ca72b2e8a53f3406d1d66f024981cefedae
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:19c9b281896ae86b8f03ac9455ba1102102711f82fad8761d50fdbd6db065555
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:932d35959c9b55fd6ab469dab071b055c65c27732a517b03d1ad3ae9ab497fae
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:e3f2e95e6eb78a059baac2aa1de8185f071bbeb0374df2394a3e1a3d3ff96ba9
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:a4306e3408afb7c6eefb172fe9ba9a9aefae589c46dca5648449197bbc087201
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:6d13f4f702b1ebc0121187212fab69ff2c7c91410a7ab9f39d94b7728b9c6d87
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:98049519826337e81dbb5081d70815c9c499cb6a609f880fbe38778f17b07457
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:313a61a0c84722f72c991923a4736f70de625e098942d39635ef7e808c3db002
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:00cfb12eb60eda2f431b05c67f03e7fa3ff53c0b391b12879be86c63dc0278ca
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:d4a3453968a9d68f2d10c3eb764cdd806064ed3add0892a841ee5c23e7853a20
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:38c842ef5c27d469cf4f6abbff936475a1237082b66dcbb55e3f04db2866c106
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:2d8196dac31f095eeb93410016ad5af717c268e3e0c6bce94e7ac44ea121f7cc
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:d9a1f4b11aec1b41de7d97fd748bb26c8cc824f7a79912b644ecf8c201551aa3
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:ea34b6a9c13fee259563fd73c10e9a0acf79bb6c2cc1251d33a8f53171df8437
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:32f2745a26673016125d674e9c5737c136ced18989691d37ff2060a6729069c9
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:b9d56976479f0b62d729877f1fa037ba938adf1f962cb15ef7aebd5fdf9436bb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:23cec97b237b306cce9eed30bf9e6a8a29c9d4ef7f4f4af13239473b7f53f177
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:e0739ac16cc2baee9690e8b369702ee67d425d5db86d1b2f2458f994d2a7dce4
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:7385b135f5400ca6706600d01af7fd624e3150dd29d28de84869d22ba1a4ee38
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
