image:
  repository: docker.io/bitnami/memcached
  pullPolicy: IfNotPresent
  tag: 1.6.38@sha256:abfff7dc2b953971d6b802f9772ebd878f3b0d1b7c04eec945d292786d78ccab

includeCommon: true
service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
portal:
  open:
    enabled: false

configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
