image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 3.6.1@sha256:0cef5348e37b07c88cf16d44f17c9df1c7dc290f665ccfd8e170c1cca05b5a53
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
portal:
  open:
    enabled: true
