image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/blender
  tag: latest@sha256:7b311d4f10a6657deb05153e26d60b124b8350b24f2200e67488f6bd307e011b
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEYBOARD: ""
            SUBFOLDER: ""
