image:
  repository: docker.io/brandawg93/peanut
  tag: 5.9.1@sha256:24ac20999bb31b0da29d70c65484975d75d3ee440881d20ea7664b106fc0116f
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NUT_HOST: "localhost"
            NUT_PORT: 3493
            USERNAME: ""
            PASSWORD: ""
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
