image:
  repository: ghcr.io/elfhosted/emby
  pullPolicy: IfNotPresent
  tag: 4.9.0.55@sha256:838453a5e4cc161952d15f00bc4131283f67514fc14a4b2504236357170853ee
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
