image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:aaf07d2069c5c5c0788db9c7d959689685f9414d891f615cd5957b51a5835779
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
