image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-09-08@sha256:a713ce09f6e2d525d6c211266b5f7b81df0a7d4c9c2e28596a490f531fc57f80
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge

portal:
  open:
    enabled: true
