image:
  repository: ghcr.io/wizarrrr/wizarr
  pullPolicy: IfNotPresent
  tag: v2025.9.7@sha256:a2475c3404d5d16d2b9f05ff70ad17612cd2e1e1088debc1bd2d3571ed4fc1f5
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            DISABLE_BUILTIN_AUTH: false
persistence:
  database:
    enabled: true
    mountPath: /data/database
  varrun:
    enabled: false
    type: emptyDir
    mountPath: /var/run
  nginxrun:
    enabled: true
    type: emptyDir
    mountPath: /run/nginx
portal:
  open:
    enabled: true
