image:
  repository: ghcr.io/wizarrrr/wizarr
  pullPolicy: IfNotPresent
  tag: v2025.9.6@sha256:82f043a514c6055ad78c5ce468bb0382f4c578412c01bb97db18955b43b5c154
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            DISABLE_BUILTIN_AUTH: false
persistence:
  database:
    enabled: true
    mountPath: /data/database
  varrun:
    enabled: false
    type: emptyDir
    mountPath: /var/run
  nginxrun:
    enabled: true
    type: emptyDir
    mountPath: /run/nginx
portal:
  open:
    enabled: true
