image:
  repository: stonith404/pingvin-share
  pullPolicy: IfNotPresent
  tag: v1.8.0@sha256:dbb9e9c6e97208323d8d8990f693c93a3e8a35cec5a0bad7ea758e8cb9a92f45

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3333
        port: 3333

persistence:
  data:
    enabled: true
    mountPath: "/opt/app/backend/data"
  image:
    enabled: true
    mountPath: "/opt/app/frontend/public/img"

portal:
  open:
    enabled: true
