image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:3bc1019c507ed43241577dd87202fb3890442f165a3ea1eb85d624e6898b93cb
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
