image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: latest@sha256:ee3b521424f480d9e829e48eb8f7df3b9348cd4f550b961f83cd4fb5667c625f
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:6ab0ac1f9b03c171013a1882c90689ba0b5bd8696f9e1d7c8a9b1da148eba5f8
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:819cc25e6e26e162a66f3a8c41e0421e4bb01cd1537ae1f4098c9b796b90268d
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:1976c3bd57d9f24dd618471e3f3070d0fb02d4e6a0017247e516bb0d8d35a572
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:c121f24b5ae762d590f81e66aaad3aa5edddcc66d9e59530f6210cc6b8202253
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:693072cdf355b6880ae97262a6b4c929f453ebda105092d974e245e97e25a299
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:aa20581366cb77eaaae7ad9a3903158891980863ea39952cfa3e9cd8d6b574a3
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:4ad2b3a305aa967240998fda66a6f94a6a23313d33f4f56fc8da39045ba5dc78
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:9e8befa2c822c00a7d0ad6f1f295523d79671ad0c907939bbdf885af65480331
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:29a6a0cc075217098ef0634e03ccfdfd583475c83e05bc02405f9033f2294b0c
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:2a9008be81153a9ba772ce455d230331a4049c3376935dbe37b04a72d8a208cc
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:430ad59cbe20cc0ca5cc73b30313fc7eebb4f0262d212f9e1f8234e4d83d3072
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:0e5e86985d7d488f5539b11d957c3dd2fcc9f9d38c0750c3e69f7f12dfeccfaa
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:02026251f04094d38b0ee7e1b6abd88f54886591115a0effb058d1cb55aa0422
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:d3045ad2cc292031d5b2b186ac2ab02745f544eeb04113d7929a0077c70d26f2
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:af7055b42fe66c8c0afc677b2ea4e4ee0c5f87bf0c03f8b8e4adac1515aa0d37
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:af1ed1a641340e4e4d5f7a12308eb758ba5ef076ee8ffa2c25342ae7800e3837
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:eb8c2c9864626ec8503c66761d5885b1919bcbe5500664f3760d3e04cf48f4d3
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:1ed4620ff752d7a2fcb2b68c515f057a6b21c7d130076e0d118a9360585e88b2
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:8988ae055e7b37781b21c46f7445d13c4f853345eb84d19854b29fec6565fd8e
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:7eafe3a42b0c95572620784281674ce7ef501ff3afad7f509feceb7de11d47a0
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:411f209c6e19acb0d16fc650cf4f1f9011ef86baf5263ae3e6aa420bf9d2de30
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:d31bd116deda0a021da949290af6684f8b31fb7d402d819563f4230bcb44c7e3
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:5bb820db6e3d851c74c6205bf6ee80d8d0d236b71bd37bf67909ce27d1ed051e
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
