image:
  repository: ghcr.io/elfhosted/jackett
  pullPolicy: IfNotPresent
  tag: 0.23.28@sha256:d18117be60827968865de4935f771bfe400274cfa68ea8d590853e6c05fcd5b2
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
