image:
  pullPolicy: IfNotPresent
  repository: docker.io/coderaiser/cloudcmd
  tag: latest@sha256:263e34e63af952dc82afd2370cac18e87575cbdb3dfef2aaea4e0305dcb32e8e
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
