image:
  repository: docker.io/machines/filestash
  tag: latest@sha256:9144bbd5bf4587caf9e4eb117163b537b03980b462ef53e84990604926a03080
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8334
        port: 8334

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APPLICATION_URL: "http://localhost:8334"
            GDRIVE_CLIENT_ID: ""
            GDRIVE_CLIENT_SECRET: ""
            DROPBOX_CLIENT_ID: ""
            ONLYOFFICE_URL: ""

persistence:
  data:
    enabled: true
    mountPath: /app/data/state

portal:
  open:
    enabled: true
