image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:70f76cd03dc5326a75bed1a1a58a69fa36cc61e49b93cd518078d5ddfe2ad551
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
