image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 3.6.5@sha256:bb4f05cf488e9cc158f25b1c72ce85167b806b7425113602a234933113efd9f8
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
portal:
  open:
    enabled: true
