image:
  pullPolicy: IfNotPresent
  repository: docker.io/shaneisrael/fireshare
  tag: v1.2.24@sha256:2f54eeec4e3bdd79be4236de7e6a3401b7c6b90f7210b5b8515e7778738fcfbb

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_KEY:
              secretKeyRef:
                name: fireshare-secrets
                key: SECRET_KEY
            MINUTES_BETWEEN_VIDEO_SCANS: 5
            ADMIN_PASSWORD: "changeme"
            # TODO ADD LDAP
            # LDAP_ENABLE: false
            # LDAP_URL: ""
            # LDAP_BINDDN: ""
            # LDAP_PASSWORD: ""
            # LDAP_BASEDN: ""
            # LDAP_USER_FILTER: ""
            # LDAP_ADMIN_GROUP: ""

service:
  main:
    ports:
      main:
        port: 10287
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data
  processeddata:
    enabled: true
    mountPath: /processed
  videos:
    enabled: true
    mountPath: /videos

portal:
  open:
    enabled: true
