image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2135@sha256:0546ceb67708cf3dcfafa4ff7d7cbd06ed6c43e6f19ce8e73af195dcd78d3062
portal:
  open:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
