image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/meeb/tubesync
  tag: latest@sha256:bf70e5d6b555f35a3311cfc9c2187d281a6a6137df9ea793d6d135a2bf4c3aed
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4848
        protocol: tcp
        targetPort: 4848
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_CONNECTION: ""
            http_PASS: ""
            http_USER: ""
            TUBESYNC_DEBUG: "False"
            TUBESYNC_HOSTS: ""
            TUBESYNC_WORKERS: "2"
