image:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0@sha256:030b2a0e3028ef0ec08884ced75b28f1f225b85bf058dcaffb8f9ffb0b9d246d
  pullPolicy: Always
j21Image:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java21@sha256:030b2a0e3028ef0ec08884ced75b28f1f225b85bf058dcaffb8f9ffb0b9d246d
  pullPolicy: Always
j21graalvmImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java21-graalvm@sha256:ba1921de1e5b0bb347a96a4be2d525b177bdb89cd1c863e65c3d51b0c77036f1
  pullPolicy: Always
j21alpineImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java21-alpine@sha256:69fe86e124f13a45ab596531b51b5de57e3f4f8123dd2a0cf75dc8e49e4186d5
  pullPolicy: Always
j17Image:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java17@sha256:56ab8661a95701ceb92bbb327b7722e000c6e01788fe6508a480b65b5ac67c38
  pullPolicy: Always
j17jdkImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always
j17graalvmImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java17-graalvm@sha256:0392a0c1a4c64b72cedb980a4c146b1213bcae9ba72e79b9d9e54cac8f4d986f
  pullPolicy: Always
j17alpineImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java17-alpine@sha256:7bd4792767649bc2ec75b757ebaa1a504fa3ee6b3a431198be65261849d5e9e4
  pullPolicy: Always
j11Image:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java11@sha256:ccb4beb26675f90f62ff5cab839e531d828607e0c1795718a3f80cddafcb0f26
  pullPolicy: Always
j8Image:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java8@sha256:4b2997fdfcd3c2d2016de06397501fbf4b1cc934d098469665f471247ec1a4df
  pullPolicy: Always
j8graalvmImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java8-graalvm-ce@sha256:203da66db89bcf1e2aaa61d54f158864a8fc2501559be64f7963fff4dea08f7f
  pullPolicy: Always
j8jdkImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2025.9.0-java8-jdk@sha256:f06c6432299c8bcd02d8ca59334257ee5e50f49995617391df8db1b43918e8d6
  pullPolicy: Always
j8alpineImage:
  repository: docker.io/itzg/minecraft-server
  tag: 2024.9.0-java8-alpine@sha256:ee8505b9670a82b7703ec35b2a87fe9b7f7823b50ae50fad18bf1fe511e577f9
  pullPolicy: Always
mcBackupImage:
  repository: docker.io/itzg/mc-backup
  tag: latest@sha256:f88c20f7acada9cd3415d568369a19127b20942cdd83fc723f393dd6996f5948
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575

mcbackup:
  zstd_params:
    - --long=25
    - --single-thread
  # comma separated list
  excludes:
    - "*.jar"
    - "cache"
    - "logs"
    - "*.tmp"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM
        mcbackup:
          enabled: true
          imageSelector: mcBackupImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            BACKUP_METHOD: "tar"
            DEST_DIR: "{{.Values.persistence.backups.mountPath }}"
            SRC_DIR: "{{.Values.persistence.data.mountPath }}"
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
            SERVER_HOST: '{{ include "tc.v1.common.lib.chart.names.fullname" $ }}'

            ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
            EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'

            INITIAL_DELAY: "2m"
            BACKUP_INTERVAL: "24h"
            PRUNE_BACKUPS_DAYS: "7"
            PAUSE_IF_NO_PLAYERS: "false"
            PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
            LINK_LATEST: "false"
            TAR_COMPRESS_METHOD: "zstd"

persistence:
  data:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /data
        mcbackup:
          mountPath: /data
          readOnly: true
  backups:
    enabled: true
    targetSelector:
      main:
        mcbackup:
          mountPath: /backups

portal:
  open:
    enabled: false
