image:
  repository: alexta69/metube
  tag: 2025-01-13@sha256:0c5c0c800ec11b8c32382ae6c84ac1581b41da850595a56b357f5628f5227ebe
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10216
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STATE_DIR: /config
            DOWNLOAD_DIR: /downloads
            OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
            YTDL_OPTIONS: "{}"
