image:
  pullPolicy: IfNotPresent
  repository: docker.io/universalmediaserver/ums
  tag: latest@sha256:de2bef9a30a9b01884d412dcfb3f0a852b271098f3e4da347e039f69d745b613
persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 5001
        protocol: tcp
        targetPort: 5001
  main:
    ports:
      main:
        port: 9001
        protocol: http
        targetPort: 9001
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 1044
        protocol: tcp
        targetPort: 1044
