image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2162@sha256:76b8678277d58014e4bcb5310fc54fa4937099ea4ae1317b6d7c1b4b50843647
portal:
  open:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
