image:
  repository: ghcr.io/linuxserver/mysql-workbench
  pullPolicy: IfNotPresent
  tag: 8.0.42@sha256:c154e4f6d5eae60ecc488831e2acd362c2bac7540cda5379e2805c66c7ea08d9
service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: http
        port: 10134
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      add:
        - IPC_LOCK
    runAsUser: 0
    runAsGroup: 0
