{
 "title": "Incomplete Data",
 "tags": [ "TeslamateCustomDashboards" ],
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Car Information 🚘",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'Car ID: ' || id as id, 'Name: '|| name as name , 'Model: '|| model as model, 'VIN: '|| vin as vin, \n  'Color: '|| exterior_color as color, 'Wheels: '|| wheel_type, 'Efficiency: '|| efficiency as efficiency \nFROM cars\nWHERE id = $car_id"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "#### Incomplete Data\n\nFrom here you can check if you have incomplete data of **Drives** and **Charges**. If so, you may follow the official guide by <a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data' target='_blank'>Manually fixing data</a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Incomplete Drives 🛣️",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Drive ID\", start_date, end_date, distance, duration_min \nFROM drives \nWHERE car_id = $car_id AND end_date is null\nORDER BY start_date DESC"
    }
   ]
  },
  {
   "title": "Incomplete Charges 🪫",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT id as \"Charging Process ID\", start_date, end_date, charge_energy_added, charge_energy_used, start_battery_level, end_battery_level, duration_min\nFROM charging_processes \nWHERE car_id = $car_id AND end_date is null\nORDER BY start_date DESC\n"
    }
   ]
  }
 ]
}