image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/kdenlive
  tag: latest@sha256:9c3177171081ba8d525d40a4f48cc6975eede54040545ff43c7e05386449bf7e
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEYBOARD: ""
            SUBFOLDER: ""
