image:
  pullPolicy: IfNotPresent
  repository: adminer
  tag: latest@sha256:bc5cf005678e04bb1bd87d65a2c4f16c63ac7d1ea6ae6471851cec7feac403dc
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ADMINER_DESIGN: ""
            ADMINER_PLUGINS: ""
service:
  main:
    ports:
      main:
        port: 18080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
