image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-11-24@sha256:8a353184837d5af99cfdb0f5b774e4b574c4c9201524a896a6a613de9a326024
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge

portal:
  open:
    enabled: true
