annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: "9.0"
dependencies:
  - name: common
    version: 25.6.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Program for forwarding ADS-B data to FlightAware
home: https://github.com/hey101/charts/stable/piaware
icon: https://truecharts.org/img/hotlink-ok/chart-icons/piaware.webp
keywords:
  - piaware
  - flight-aware
  - flight-tracker
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: piaware
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/piaware
  - https://github.com/flightaware/piaware
  - https://github.com/truecharts/charts/tree/master/charts/stable/piaware
  - https://hub.docker.com/r/mikenye/piaware
type: application
version: 14.4.4
