image:
  repository: ghcr.io/linuxserver/calibre
  tag: 8.8.0@sha256:739eadb90c74d12db8ac1f6ad7b59fa13f76b64f2343eb188abfd813bcff8be2
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: http
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
