image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/autoscan
  tag: latest@sha256:204a4b9548c6318c8c1bfeedd49df13647b1bed5f434cb0cf2d2b3f6fa06673e
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3030
        protocol: http
        targetPort: 3030
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PLEX_LOGIN: ""
            PLEX_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
