image:
  pullPolicy: IfNotPresent
  repository: adminer
  tag: latest@sha256:d93327eaa9a26571b1b3dfa99e67734949a8924328f180f7a0c773b1eb53bc8d
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ADMINER_DESIGN: ""
            ADMINER_PLUGINS: ""
service:
  main:
    ports:
      main:
        port: 18080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
