image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2353@sha256:f2efd8cc2e521579064188fa1daecf4eefa2839f96dd4c9973e8c8853d42d1e2
portal:
  open:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
