image:
  repository: ghcr.io/elfhosted/jackett
  pullPolicy: IfNotPresent
  tag: 0.22.2223@sha256:ecc6fa4294a29e8ac9cf67e8e47502c91f488885725579dc27d8aede7fd19331
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
