image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:8a5df77aae23aa433938f9cb499c29f71c12e1c3735e03bcd46a595d8833ab53
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:097a293f0822f196a63cbc033189c83e368be012369fd0919fb912f689092582
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:1df2dc5b954770c2e2140fa38b4a7cebcf5b0eb3149ed598d248bcc674a23019
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:5000fb3de826141a7acef2e85f3c6d55887e390c3017b941272aaef03d70137e
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:0217885e7e1bfc70cdbaf5e4fc1afe2e2f7be098dcb72a084c7f22e7f155537a
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:7af2a830fc2eeeb9cd2810d375c332882df827afc61e08680326c3494f7ff162
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:c6881526b1291b360376c1c518393020a03c7b3be40b2a90fe9d0d543a401200
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:ebc08f4df93a8c3455bd433c088b8095025418d00f5548ff8a5cf7d69bb48032
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:e06a4f4ab76b08838f904be4e37fbf38c17e6dd5b82fa1ecd4840453684f4644
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:db987cf3e695b83ba9665f85b6e56dda99bddbbefe16e5d5a9a0c261ac0ca729
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:812f2f901e5745cb2640183cac119e01bbbc706007f2b0b8c1420182166df141
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:e54abcce28cc5b9001094c8befe64bda54e47efb35699232385bbbae671f5744
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:1cd1fdce9a83a772bbf71e70800fa237036bada79b4c09b319f17b84ca281207
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:ed66e8c0278a3473f1c7dbfbab4fb3f3a46af97c0f4a5c88a8d3aa7163337ada
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:e3bec5680b0038e88ee9c90153ccbc78ac49fb98a54cfec7b4e158586e474ce3
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:4c1bbf2fa3342568199f22779dfb7532f6a149e86c231fd37a8711fa78f79026
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:da00e0a49b1b4ada56d7cb7a27334f0acf4e18498c0129d804445c792a25ce90
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:fd6322677b8ea6ab6de3bafd20eab2a298c7d7b8c38628649c12d3f3eddd54c2
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:b2df902af6f5d0f85f7fc409d786297773991748ec3d71bb076964b704ca3af6
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:4bd8ca2ed93456957bcdb6f92aba10f4fc111f73b17c261b46511ca5d4f05742
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:93de06298f10af9b03fbbd6fa7db68d3d64f6e2d1154d78457796362e89ac827
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:bd28efc37ebcab70303ba460048d0dd060c53d514b5720c903005f8b837751de
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:6c4d2d1464bc5c2d90e523ccf190ac853076e691ecb05fc4c2e24d059e281540
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:a7a2a142b770560b23db4d06a66653445181296a839441a2bdbb4f6a770c7125
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
