image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:e16e1839e466e75bd1bc1c34035329cfc2a59dfeca8c6effb310e987cbb202a7
persistence:
  download:
    enabled: true
    mountPath: /download
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
