image:
  repository: ghcr.io/linuxserver/mysql-workbench
  pullPolicy: IfNotPresent
  tag: 8.0.42@sha256:0015840f127b9d63157a3affbaa0f2ee75e23865f7f793dbeb80b5f8a2f2ea75
service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: http
        port: 10134
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      add:
        - IPC_LOCK
    runAsUser: 0
    runAsGroup: 0
