image:
  pullPolicy: IfNotPresent
  repository: docker.io/phasecorex/red-discordbot
  tag: full@sha256:ffb3d6f6d7337af68c505952d1570e49dc53feb0f70e2a800113151b4485a096
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PREFIX: ""
            TOKEN: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
