image:
  pullPolicy: IfNotPresent
  repository: docker.io/petersem/posterr
  tag: latest@sha256:b9553bdfea4eb121cdd5db876aa3916d534a6c299cba259a2f85656609a3d853
service:
  main:
    ports:
      main:
        port: 9876
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /usr/src/app/config
  custom:
    enabled: true
    mountPath: /usr/src/app/public/custom
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
