image:
  repository: itzg/mc-router
  pullPolicy: IfNotPresent
  tag: 1.27.2@sha256:a2e51b29b4ab1ebfd353f008a23ccd6c878e00ac9d95d7af5238c1a68bb77a23
service:
  main:
    ports:
      main:
        port: 25564
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25565
mcrouter:
  host_minecraft: []
  #  - "minecraft.local=minecraft-java.ix-minecraft-java.svc.cluster.local:25565"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secrets"
          env:
            API_BINDING: ":{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.minecraft.ports.minecraft.port }}"
portal:
  open:
    enabled: false
