image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:22b7d88626e852229267db1f4cdd021186b448bd227aa6999bd389a9d92306dc
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:5afeaa6033c3e659faac5b27dce197fab304332963269a4db37c427e9865a29f
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:06f4e72617392d80997702d829e8b47b018a122abf1b3d9e16cc224e7a104d2b
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:5000fb3de826141a7acef2e85f3c6d55887e390c3017b941272aaef03d70137e
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:d51950b907cd8d0c6ce4a2277d47f76008638e981cf13e2092f2a84c55b8004c
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:571cf2a277fa401d006fd697929d27c77cb497c00eaf676fdea86e4b3a6a2968
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:c81ed038121aeb51b7862c9a635e679176272611f437db8e4f38ecb1b964a44e
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:ebc08f4df93a8c3455bd433c088b8095025418d00f5548ff8a5cf7d69bb48032
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:e06a4f4ab76b08838f904be4e37fbf38c17e6dd5b82fa1ecd4840453684f4644
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:716fc28bd39625e0e2fa21fabc759abf57c7bb914193d8638a60f280944f4e71
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:91760d549db8a1d1d88da5acc91446494baa7db2607a43de6fb0ddf05f85fb26
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:e54abcce28cc5b9001094c8befe64bda54e47efb35699232385bbbae671f5744
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:6526501485cf3a6bfe7bf7bc5635f7f151f6e0fb33bd4b1e0c507bc6211fe7ed
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:28089df216ac8c394eed880d7eb2e82bf835991b2d1b5ee0f7659959ffd215cc
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:56e52a4ee8c8f43cc62aa0fb3713a986741fa2409d0673a8a958a30da46520e1
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:4c1bbf2fa3342568199f22779dfb7532f6a149e86c231fd37a8711fa78f79026
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:3ef53ca887ae8d54eec1c012e4e0d081e5c06a036da8212078d586e46bef5188
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:a75301fe92f3a35c346e893167672180c8f0f748752d455b0bfabb86a50e8b39
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:56e583da788efbf4437938b908b2803b656fb37909080734cb20e07cdff0986f
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:4bd8ca2ed93456957bcdb6f92aba10f4fc111f73b17c261b46511ca5d4f05742
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:13009b56e54471917e6d54623b5b4542f292a964d4d403a234f1fa93190c328e
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:88971f557702f53e1d3b2801be7d5ade711ebdc8474aa7ef650c74bcfbbbf555
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:e3d7376c9f30763310b5e35c74d37aa1617fa1da85998b1b4428edd25e6e80e6
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:a7a2a142b770560b23db4d06a66653445181296a839441a2bdbb4f6a770c7125
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
