image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: latest@sha256:ee3b521424f480d9e829e48eb8f7df3b9348cd4f550b961f83cd4fb5667c625f
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:3290c7bc75b50e45ce3ea2867da9c58ece568e1ac0ba97abaa1fc65108820641
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:5bd01eab92761a1220295f50bf3b3606f10e7095699447ef5b5844dd4098fba3
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:eae9f8a2de09c9cd1e3f08c68c7dc16540edc9d31460368f1e2559024d1e6374
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:c121f24b5ae762d590f81e66aaad3aa5edddcc66d9e59530f6210cc6b8202253
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:2f936bf9b942a45aba276388b65c81a3b732e11ce48d9430a0b273a591612519
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:7d415559319f890c7d43df63c29e640e1b4869188a4105974da85adcc1d226b5
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:44b5f29b7552101c5eb0fb581f7dc957348544783da106d98d8975cda05f7b2a
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:9e8befa2c822c00a7d0ad6f1f295523d79671ad0c907939bbdf885af65480331
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:ab2f2a79224d010a27c531b715dacd9d03d8e070f92fbf9d975ba5d79f9492a5
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:ba0417f7a1fb2298066124f4cbdf4e8e5e534fbb61aba16e0b94b22a8d9b76d6
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:003cb1f171ae72c12b8bdf080318885cdb1f66443ab1ee2daa9ab69e2bd5d632
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:0e5e86985d7d488f5539b11d957c3dd2fcc9f9d38c0750c3e69f7f12dfeccfaa
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:145629300d4a96a87d643042821c4dc60ff7f9feda300b47341eeff1227bea79
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:b9db39984ff7aa7da81e83dc99485eab987a48c52c6d013fd3478a4d9d0e27da
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:d7a996c5864e24e104aac111d346a8e63384c959fe0606487a5e3151d288f38e
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:af1ed1a641340e4e4d5f7a12308eb758ba5ef076ee8ffa2c25342ae7800e3837
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:4d53aae53d3050ac8ab494f86ad394584c0023b2da613a463b81d02e313ddcfb
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:d42139608247bf82720cc730b9a0248987e5e10e7aa34910abae3176f868d652
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:f9d48beaa7cc1c640623815bbfc47584eb58381d424803decda407aa02c2e23e
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:7eafe3a42b0c95572620784281674ce7ef501ff3afad7f509feceb7de11d47a0
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:264f4e7fbbeb87678fbf947941045c1b66e6f7b69356d5ac519415b27475d6ee
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:02d7a80a7c5c18b172cbb6ab968ab63233851b2b132ff091b8cee28144904a39
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:b07e8424ac63edc8eec1f03c48d8e847064f850e828b0e7818a36ab6c081a9e3
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
