image:
  repository: victoriametrics/victoria-metrics
  tag: v1.109.0@sha256:bc9dd962b284e8034fc2dbb87deb2aad4ba8ff7430fe88e301913d1b6e0df1ea
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8428
        targetPort: 8428
persistence:
  data:
    enabled: true
    mountPath: /victoria-metrics-data
    targetSelectAll: true
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health
            readiness:
              type: http
              path: /health
            startup:
              enabled: false
