image:
  repository: rssbridge/rss-bridge
  tag: 2025-01-02@sha256:59e659ca48fe45ce76f8992b2b2ae413dc0e2a9fb7a411d37b6df4a489f2a64d
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10225
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"
