image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/autoscan
  tag: latest@sha256:593db74e95797b0576dad32f0ad296f7b653bf3ead8e4edc18d5dbc04b821547
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3030
        protocol: http
        targetPort: 3030
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PLEX_LOGIN: ""
            PLEX_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
