image:
  repository: ghcr.io/elfhosted/jackett
  pullPolicy: IfNotPresent
  tag: 0.23.62@sha256:3578cccd158c70da6419e9f1fce9c730708edc6e66f2240f9006155f2e44fdc7
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
