image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:1bf47c0a0823b4ae9819a3262c6ed00de497b1b1dbfe84da089e849d743cd24d
persistence:
  download:
    enabled: true
    mountPath: /download
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
