image:
  repository: docker.io/jgraph/drawio
  tag: 28.0.5@sha256:7f34fa44685ebcf7263654e4add2e5120b7fb0cdcd02b1120e174d3e578670a8
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
portal:
  open:
    enabled: true
