image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 3.6.5@sha256:56a7877b22e5606428a7c63f13f477bc5cb342bcd19e1ca4eb2080225316438e
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
portal:
  open:
    enabled: true
