image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: 1.4.35@sha256:32fdffa2488b21314e5c305f33dfab036a06d8ac0cb028e654ac5c30c9b903f7
service:
  main:
    ports:
      main:
        port: 10042
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
