image:
  repository: ghcr.io/linuxserver/sickchill
  pullPolicy: IfNotPresent
  tag: 2024.3.1@sha256:790f20ddc60e5cff26a6a875543a9f7127783dc02ab60132d6ee0889c5e923e3
service:
  main:
    ports:
      main:
        port: 10067
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
