image:
  pullPolicy: IfNotPresent
  repository: docker.io/wabayang/jelu
  tag: latest@sha256:258c65f00f95b0557f2ceef7194ead6650994b5f11cf0dd8f089ee6fc964edf2
persistence:
  config:
    enabled: true
    mountPath: /config
  databasepath:
    enabled: true
    mountPath: /database
  imagespath:
    enabled: true
    mountPath: /files/images
  importspath:
    enabled: true
    mountPath: /files/imports
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 11111
        protocol: tcp
        targetPort: 11111
