annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: test
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: "3.3.2"
dependencies:
  - name: common
    version: 26.4.1
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Container for proxmox backup server
home: https://github.com/hey101/charts/stable/proxmox-backup-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/proxmox-backup-server.webp
keywords:
  - proxmox-backup-server
  - pbs
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: proxmox-backup-server
sources:
  - https://github.com/hey101/charts/tree/master/charts/stable/proxmox-backup-server
  - https://github.com/truecharts/charts/tree/master/charts/stable/proxmox-backup-server
  - https://hub.docker.com/r/ayufan/proxmox-backup-server
type: application
version: 5.5.10
