image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/autoscan
  tag: latest@sha256:43d24835d205483e0ab9c2f306deb7c14b979616a00dc1d3e16888a49467f2c3
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3030
        protocol: http
        targetPort: 3030
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            PLEX_LOGIN: ""
            PLEX_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
